[package]
name = "jinn-slices"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
parking_lot = { workspace = true }
derive_more = { workspace = true }
jinn-theme = { workspace = true }
dashmap = { workspace = true }
jinn-core-types = { workspace = true }
jiff = { workspace = true }
kameo = { workspace = true }
kameo_actors = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true }
trouper = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
wherror = { workspace = true }
error-stack = { workspace = true }
uuid = { workspace = true }
dirs = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
