[package]
name = "jinn-term-msg"
version.workspace = true
edition.workspace = true

[dependencies]
jinn-core-types = { workspace = true }
kameo = { workspace = true }
trouper = { workspace = true }
jinn-slices = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
ratatui = { workspace = true }
ratatui-which-key = { workspace = true }
wherror = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
