[package]
name = "jinn-mcp-msg"
version.workspace = true
edition.workspace = true
[dependencies]
jinn-core-types = { workspace = true }
jinn-slices = { workspace = true }
trouper = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
error-stack = { workspace = true }
wherror = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
