//! Shared infrastructure - services, core coordination, state, and projections.

// Re-export shared infra that now lives in the `jinn-common` leaf crate.
pub use jinn_common::{app_info, app_paths, process_kill, system_resource, toml_patch};

pub mod actor_deps;
pub mod app_state;
pub mod bridge;
pub mod bus;
pub mod core;
pub mod frontend_projection;
pub mod phase_command;
pub mod phase_events;
pub mod render_ctx;
pub mod request_dump;
pub mod services;
pub mod session_projection;
pub mod slices;
pub mod state;
pub mod ui_element;
pub mod ui_element_fake;
pub mod ui_registry;

/// Standard UI registry type for the jinn application.
pub type AppUiRegistry = ui_registry::UiRegistry;

/// Register the UI elements the kernel itself owns.
///
/// Called once during application startup. Slice-owned elements are
/// registered by composition in `jinn-tui`, which can reference slice
/// crates; the kernel cannot.
pub fn register_all_ui_elements(_registry: &mut AppUiRegistry) {
    // Every display element is slice-owned now, so composition in `jinn-tui`
    // registers them all. This function survives as the kernel's hook for
    // elements it owns itself, of which there are currently none.
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::panic,
        clippy::unreachable,
        clippy::string_slice,
        clippy::uninlined_format_args,
        reason = "test code"
    )]
    // Targeted import (not `use super::*`): the glob would pull this module's
    // child module named `core` into scope, shadowing the `core` crate inside
    // macro-expanded paths (`core::time::Duration`, as generated by rstest).
    use super::{AppUiRegistry, register_all_ui_elements};

    #[rstest::rstest]
    #[test]
    fn register_all_ui_elements_registers_nothing_by_itself() {
        // Given an empty registry.
        let mut registry = AppUiRegistry::new();

        // When registering the kernel's own UI elements.
        register_all_ui_elements(&mut registry);

        // Then it adds nothing: every display element is slice-owned, and
        // composition in jinn-tui registers those. This is the assertion that
        // keeps a slice element from being re-added here, which would render
        // it twice.
        assert_eq!(registry.iter_mut().count(), 0);
    }
}
