[package]
name = "jinn-sidebar-msg"
version.workspace = true
edition.workspace = true
[dependencies]
ratatui = { workspace = true }
jiff = { workspace = true }
jinn-core-types = { workspace = true }
jinn-slices = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
