[package]
name = "jinn-provider-config"
version.workspace = true
edition.workspace = true

[dependencies]
# Internal deps
jinn-preferences-config = { workspace = true }
jinn-provider = { workspace = true }
jinn-common = { workspace = true }

# External deps
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
jiff = { workspace = true }
parking_lot = { workspace = true }
dirs = { workspace = true }
tracing = { workspace = true }
error-stack = { workspace = true }
wherror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
