[package]
name = "jinn-chat-input"
version.workspace = true
edition.workspace = true

[dependencies]
jinn-chat-input-msg = { workspace = true }
jinn-slices = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tokio = { workspace = true }
jinn-domain = { workspace = true }

[lints]
workspace = true
